# Utilizando dados de MoCap do banco de dados MoVi em Python

--> O banco de dados MoVi é originalmente fornecido através da extensão .mat.

--> O banco fornece algumas funções de utilidades para tornar mais fácil a leitura dos arquivos MoVi no ambiente Python.

In [1]:
from utils import *
%load_ext autoreload
%autoreload 2
%matplotlib inline

--> Abaixo, insira o seu caminho da pasta Movi-Toolbox que contenha o vídeo do sujeito escolhido. Observe que neste caso, foi escolhido o sujeito 15. Escolha o vídeo que esteja com o nome nesse formato: "F_v3d_Subject_XX.mat"

--> Caso apareça algum erro na leitura do arquivo ao rodar a linha de código abaixo, acrescente a letra r antes das aspas simples, como mostrado abaixo.

In [2]:
# File location

v3d_filename = r'C:\Users\gusta\OneDrive\Documentos\Users\Gustavo Monteiro\Documents\GitHub\MoVi-Toolbox\MoCap\F_v3d_Subject_15.mat' 

--> Abaixo, é apenas a leitura do arquivo MoVi, indicando as chaves que ele contém: id, sujeito e movimento.

In [3]:
# Reading MoVi files as a Python dictionary
sample = mat2dict(v3d_filename)
sample.keys()

dict_keys(['id', 'subject', 'move'])

--> Mostrando as chaves do dicionário que podem ser acessadas.

In [4]:
# Printing the dictionary keys in a tree style
pretty_dict(sample, print_type=False, indent=1)

	Key: id
	Key: subject
		Key: id
		Key: sex
		Key: handedness
		Key: height
		Key: mass
		Key: age
	Key: move
		Key: description
		Key: markerName
		Key: markerType
		Key: markerDescription
		Key: markerSide
		Key: markerMatch
		Key: segmentName
		Key: segmentType
		Key: segmentDescription
		Key: segmentSide
		Key: segmentMatch
		Key: segmentParent
		Key: physicalMarkers
		Key: virtualMarkers
		Key: lcData
		Key: flags30
		Key: flags120
		Key: motions_list
		Key: markerGaps
		Key: virtualMarkerParent
		Key: markerLocation
		Key: virtualMarkerLocation
		Key: jointsAffine_v3d
		Key: jointsTranslation_v3d
		Key: jointsExpMaps_v3d
		Key: jointsGaps_v3d


--> Printando a identificação do sujeito do vídeo escolhido

In [5]:
print('ID: ',sample['id'])
print(sample['subject'])

ID:  Subject_15
{'id': 'Subject_15', 'sex': 'male', 'handedness': 'right', 'height': 181, 'mass': 72, 'age': 21}


--> Mostrando apenas as chaves de movimento

In [6]:
# First move sample
move = sample['move']
pretty_dict(move)

Key: description
Key: markerName
Key: markerType
Key: markerDescription
Key: markerSide
Key: markerMatch
Key: segmentName
Key: segmentType
Key: segmentDescription
Key: segmentSide
Key: segmentMatch
Key: segmentParent
Key: physicalMarkers
Key: virtualMarkers
Key: lcData
Key: flags30
Key: flags120
Key: motions_list
Key: markerGaps
Key: virtualMarkerParent
Key: markerLocation
Key: virtualMarkerLocation
Key: jointsAffine_v3d
Key: jointsTranslation_v3d
Key: jointsExpMaps_v3d
Key: jointsGaps_v3d


--> Convertendo as chaves do dicionário em um tipo tupla para que os atributos sejam acessíveis utilizando um ponto depois da função.

--> Aqui você pode escolher mostrar quais são os marcadores físicos, virtuais, a descrição de cada um deles e a lista de movimentos executados pelo indivíduo.

In [7]:
# dict2ntuple function can be used to convert the dictionary to a namedtuple 
# so that the attributes are accessible by dotted notation
move =dict2ntuple(move)
print(move.markerDescription)
print(move.physicalMarkers)
print(move.virtualMarkers)
print(move.motions_list)

['Back of Neck' 'Upper Back' 'Clavicle' 'Sternum' 'Umbilicus'
 'Left Front Head' 'Left Back Head' 'Left Back' 'Left Shoulder'
 'Left Upper Arm' 'Left Elbow' 'Left Forearm' 'Left Wrist Bar Thumb Side'
 'Left Wrist Bar Pinkie Side' 'Left Finger' 'Left ASIS' 'Left PSIS'
 'Left Front Thigh' 'Left Thigh' 'Left Knee' 'Left Ankle' 'Left Heel'
 'Left 5th Metatarsal' 'Left Toe' 'Left Cheek' 'Left Breast'
 'Left Inner Elbow' 'Left Waist' 'Left Thomb' 'Left Front Inner Thigh'
 'Right Inner Knee' 'Left Shin' 'RLeft First Metatarsal' 'Left Forth Toe'
 'Left Scapula' 'Left Bum' 'Right Front Head' 'Right Back Head'
 'Right Back' 'Right Shoulder' 'Right Upper Arm' 'Right Elbow'
 'Right Forearm' 'Right Wrist Bar Thumb Side'
 'Right Wrist Bar Pinkie Side' 'Right Finger' 'Right ASIS' 'Right PSIS'
 'Right Front Thigh' 'Right Thigh' 'Right Knee' 'Right Ankle' 'Right Heel'
 'Right 5th Metatarsal' 'Right Toe' 'Right Cheek' 'Right Breast'
 'Right Inner Elbow' 'Right Waist' 'Right Thomb'
 'Right Front Inner Th

## Armazenar os dados de posição dos marcadores em cada frame do vídeo em um array

--> Abaixo, temos os dados de TODOS os marcadores em TODOS os frames do vídeo escolhido.

--> Observe que são dados de milhares de frames e o notebook não mostra todos eles, mas coloca as reticências para evidenciar.

--> Observe também que são blocos de array dentro de um array principal, que representam os marcadores (array principal) e suas posições em cada frame (blocos de array internos).

In [8]:
move.markerLocation

array([[[ 336.98776245,   17.4847908 , 1559.65722656],
        [ 307.49227905,   20.96870995, 1235.98718262],
        [ 466.79177856,   24.70891571, 1497.18261719],
        ...,
        [ 356.89865112, -166.20855713, 1462.76721191],
        [ 487.96240234, -695.30969238, 1474.58483887],
        [ 535.75872803,  -89.18184662,   11.15608311]],

       [[ 336.91867065,   17.47442055, 1559.62512207],
        [ 307.44500732,   20.97799873, 1236.01245117],
        [ 466.72747803,   24.72114944, 1497.20153809],
        ...,
        [ 356.89349365, -166.20951843, 1462.75097656],
        [ 488.02035522, -695.31994629, 1474.49694824],
        [ 535.76281738,  -89.28752136,   11.33196163]],

       [[ 336.85165405,   17.46774292, 1559.61340332],
        [ 307.38452148,   20.97657204, 1236.02563477],
        [ 466.66177368,   24.71905136, 1497.2244873 ],
        ...,
        [ 356.87591553, -166.23568726, 1462.76635742],
        [ 488.07287598, -695.32769775, 1474.41381836],
        [ 535.77148438

--> O trecho de código abaixo printa apenas a primeira e terceira colunas, que são os dados de posição (dados em milímetros) dos eixos horizontal e vertical, respectivamente.

In [9]:
markerLocation_output = np.delete(move.markerLocation, np.s_[0:1], axis=2)
print(markerLocation_output)

[[[  17.4847908  1559.65722656]
  [  20.96870995 1235.98718262]
  [  24.70891571 1497.18261719]
  ...
  [-166.20855713 1462.76721191]
  [-695.30969238 1474.58483887]
  [ -89.18184662   11.15608311]]

 [[  17.47442055 1559.62512207]
  [  20.97799873 1236.01245117]
  [  24.72114944 1497.20153809]
  ...
  [-166.20951843 1462.75097656]
  [-695.31994629 1474.49694824]
  [ -89.28752136   11.33196163]]

 [[  17.46774292 1559.61340332]
  [  20.97657204 1236.02563477]
  [  24.71905136 1497.2244873 ]
  ...
  [-166.23568726 1462.76635742]
  [-695.32769775 1474.41381836]
  [ -89.28872681   11.34207153]]

 ...

 [[  39.77682495 1558.72497559]
  [  54.44635391 1231.61975098]
  [  42.31341171 1481.25195312]
  ...
  [-178.26251221 1372.22790527]
  [-148.35076904  880.42681885]
  [ -79.08763885   10.83769035]]

 [[  39.73885345 1558.7355957 ]
  [  54.4423027  1231.60705566]
  [  42.16498184 1481.10180664]
  ...
  [-178.2865448  1372.25891113]
  [-148.28422546  880.45904541]
  [ -79.09062195   10.843556

--> Salve seus dados em um arquivo que você pode nomear como quiser, neste caso o nome é 'Sensor data'

In [10]:
np.save('Sensor data', markerLocation_output)

--> Abaixo, rode o código para mostrar o tamanho do seu array

In [11]:
d3_array = markerLocation_output
size = len(d3_array)
d3_array.shape

(17846, 87, 2)